/* ── STATION DATA ── */
const STATIONS = [
  /* Hit Music */
  {name:"Big Top 40",                  cat:"Hit Music",   url:"https://media-ice.musicradio.com/BigTop40MP3"},
  {name:"Capital UK",                  cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalUKMP3"},
  {name:"Capital London",              cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalMP3"},
  {name:"Capital Anthems",             cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalAnthemsMP3"},
  {name:"Capital Dance",               cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalDanceMP3"},
  {name:"Capital Chill",               cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalChillMP3"},
  {name:"Capital XTRA UK",             cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalXTRANationalMP3"},
  {name:"Capital XTRA London",         cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalXTRALondonMP3"},
  {name:"Capital XTRA Reloaded",       cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalXTRAReloadedMP3"},
  {name:"Capital Birmingham",          cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalBirminghamMP3"},
  {name:"Capital Brighton",            cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalBrightonMP3"},
  {name:"Capital Edinburgh",           cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalEdinburghMP3"},
  {name:"Capital Glasgow",             cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalGlasgowMP3"},
  {name:"Capital Liverpool",           cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalLiverpoolMP3"},
  {name:"Capital Manchester",          cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalManchesterMP3"},
  {name:"Capital South Coast",         cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalSouthCoastMP3"},
  {name:"Capital South Wales",         cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalSouthWalesMP3"},
  {name:"Capital Yorkshire (East)",    cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalYorkshireEastMP3"},
  {name:"Capital Yorkshire (S&W)",     cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalYorkshireSouthWestMP3"},
  {name:"Capital Lancashire (Preston)",cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalPrestonMP3"},
  {name:"Capital Tyne & Wear",         cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalTyneWearMP3"},
  {name:"Capital Teesside",            cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalTeessideMP3"},
  {name:"Capital Derbyshire",          cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalDerbyshireMP3"},
  {name:"Capital Leicestershire",      cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalLeicestershireMP3"},
  {name:"Capital Nottinghamshire",     cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalNottinghamshireMP3"},
  {name:"Capital Coventry",            cat:"Hit Music",   url:"https://media-ice.musicradio.com/CapitalCoventryMP3"},

  /* Heart */
  {name:"Heart UK",                    cat:"Heart",       url:"https://media-ice.musicradio.com/HeartUKMP3"},
  {name:"Heart London",                cat:"Heart",       url:"https://media-ice.musicradio.com/HeartLondonMP3"},
  {name:"Heart Dance",                 cat:"Heart",       url:"https://media-ice.musicradio.com/HeartDanceMP3"},
  {name:"Heart Love",                  cat:"Heart",       url:"https://media-ice.musicradio.com/HeartLoveMP3"},
  {name:"Heart Musicals",              cat:"Heart",       url:"https://media-ice.musicradio.com/HeartMusicalsMP3"},
  {name:"Heart 70s",                   cat:"Heart",       url:"https://media-ice.musicradio.com/Heart70sMP3"},
  {name:"Heart 80s",                   cat:"Heart",       url:"https://media-ice.musicradio.com/Heart80sMP3"},
  {name:"Heart 90s",                   cat:"Heart",       url:"https://media-ice.musicradio.com/Heart90sMP3"},
  {name:"Heart 00s",                   cat:"Heart",       url:"https://media-ice.musicradio.com/Heart00sMP3"},
  {name:"Heart 10s",                   cat:"Heart",       url:"https://media-ice.musicradio.com/Heart10sMP3"},
  {name:"Heart Bristol",               cat:"Heart",       url:"https://media-ice.musicradio.com/HeartBristolMP3"},
  {name:"Heart Hampshire",             cat:"Heart",       url:"https://media-ice.musicradio.com/HeartHampshireMP3"},
  {name:"Heart Kent",                  cat:"Heart",       url:"https://media-ice.musicradio.com/HeartKentMP3"},
  {name:"Heart Sussex",                cat:"Heart",       url:"https://media-ice.musicradio.com/HeartSussexMP3"},
  {name:"Heart Essex",                 cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartEssexMP3"},
  {name:"Heart Norfolk",               cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartNorfolkMP3"},
  {name:"Heart Suffolk",               cat:"Heart",       url:"https://media-ice.musicradio.com/HeartSuffolkMP3"},
  {name:"Heart Yorkshire",             cat:"Heart",       url:"https://media-ice.musicradio.com/HeartYorkshireMP3"},
  {name:"Heart West Midlands",         cat:"Heart",       url:"https://media-ice.musicradio.com/HeartWestMidsMP3"},
  {name:"Heart Leicestershire",        cat:"Heart",       url:"https://media-ice.musicradio.com/HeartLeicestershireMP3"},
  {name:"Heart Nottinghamshire",       cat:"Heart",       url:"https://media-ice.musicradio.com/HeartNottinghamshireMP3"},
  {name:"Heart North West",            cat:"Heart",       url:"https://media-ice.musicradio.com/HeartNorthWestMP3"},
  {name:"Heart Scotland (East)",       cat:"Heart",       url:"https://media-ice.musicradio.com/HeartEdinburghMP3"},
  {name:"Heart Scotland (West)",       cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartGlasgowMP3"},
  {name:"Heart Wales (South)",         cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartSouthWalesMP3"},
  {name:"Heart Cornwall",              cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartCornwallMP3"},
  {name:"Heart Devon (Exeter)",        cat:"Heart",       url:"https://media-ice.musicradio.com/HeartEastDevonMP3"},
  {name:"Heart Plymouth",              cat:"Heart",       url:"https://media-ice.musicradio.com/HeartPlymouthMP3"},
  {name:"Heart Dorset",                cat:"Heart",       url:"https://media-ice.musicradio.com/HeartDorsetMP3"},
  {name:"Heart Wiltshire",             cat:"Heart",       url:"https://media-ice.musicradio.com/HeartWiltshireMP3"},
  {name:"Heart Oxfordshire",           cat:"Heart",       url:"https://media-ice.musicradio.com/HeartOxfordshireMP3"},
  {name:"Heart Berkshire",             cat:"Heart",       url:"https://media-ice.musicradio.com/HeartBerkshireMP3"},
  {name:"Heart Cambridgeshire",        cat:"Heart",       url:"https://media-ice.musicradio.com/HeartCambridgeMP3"},
  {name:"Heart Peterborough",          cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartPeterboroughMP3"},
  {name:"Heart Bath",                  cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartBathMP3"},
  {name:"Heart Gloucestershire",       cat:"Heart",       url:"https://media-ice.musicradio.com/ HeartGloucestershireMP3"},
  {name:"Heart Somerset",              cat:"Heart",       url:"https://media-ice.musicradio.com/HeartSomersetMP3"},
  {name:"Heart Northamptonshire",      cat:"Heart",       url:"https://media-ice.musicradio.com/HeartNorthamptonshireMP3"},

  /* Smooth */
  {name:"Smooth UK",                   cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothUKMP3"},
  {name:"Smooth London",               cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothLondonMP3"},
  {name:"Smooth Chill",                cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothChillMP3"},
  {name:"Smooth Relax",                cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothRelaxMP3"},
  {name:"Smooth Soul",                 cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothSoulMP3"},
  {name:"Smooth Country",              cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothCountryMP3"},
  {name:"Smooth 70s",                  cat:"Smooth",      url:"https://media-ice.musicradio.com/Smooth70sMP3"},
  {name:"Smooth 80s",                  cat:"Smooth",      url:"https://media-ice.musicradio.com/Smooth80sMP3"},
  {name:"Smooth Scotland",             cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothScotlandMP3"},
  {name:"Smooth North West",           cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothNorthWestMP3"},
  {name:"Smooth North East (T&W)",     cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothNorthEastNMP3"},
  {name:"Smooth East Midlands",        cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothEastMidsMP3"},
  {name:"Smooth West Midlands",        cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothWestMidsMP3"},
  {name:"Smooth Hampshire",            cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothHampshireMP3"},
  {name:"Smooth Kent",                 cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothKentMP3"},
  {name:"Smooth Sussex",               cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothSussexMP3"},
  {name:"Smooth Essex",                cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothEssexMP3"},
  {name:"Smooth Norfolk",              cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothNorfolkMP3"},
  {name:"Smooth Suffolk",              cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothSuffolkMP3"},
  {name:"Smooth Bristol",              cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothBristolMP3"},
  {name:"Smooth Gloucester",           cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothGloucesterMP3"},
  {name:"Smooth Dorset",               cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothDorsetMP3"},
  {name:"Smooth Wiltshire",            cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothWiltshireMP3"},
  {name:"Smooth Berkshire",            cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothBerkshireMP3"},
  {name:"Smooth Plymouth",             cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothPlymouthMP3"},
  {name:"Smooth South Wales",          cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothSouthWalesMP3"},
  {name:"Smooth Lake District",        cat:"Smooth",      url:"https://media-ice.musicradio.com/SmoothLakeDistrictMP3"},

  /* Classical */
  {name:"Classic FM",                  cat:"Classical",   url:"https://media-ice.musicradio.com/ClassicFMMP3"},
  {name:"Classic FM Calm",             cat:"Classical",   url:"https://media-ice.musicradio.com/ClassicFMCalmMP3"},
  {name:"Classic FM Movies",           cat:"Classical",   url:"https://media-ice.musicradio.com/ClassicFMMoviesMP3"},

  /* Rock & Indie */
  {name:"Radio X UK",                  cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioXUKMP3"},
  {name:"Radio X London",              cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioXLondonMP3"},
  {name:"Radio X Manchester",          cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioXManchesterMP3"},
  {name:"Radio X Classic Rock",        cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioXClassicRockMP3"},
  {name:"Radio X Chilled",             cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioXChilledMP3"},
  {name:"Radio X 90s",                 cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioX90sMP3"},
  {name:"Radio X 00s",                 cat:"Rock & Indie", url:"https://media-ice.musicradio.com/RadioX00sMP3"},

  /* Talk & News */
  {name:"LBC UK",                      cat:"Talk & News", url:"https://media-ice.musicradio.com/LBCUKMP3"},
  {name:"LBC London",                  cat:"Talk & News", url:"https://media-ice.musicradio.com/LBCLondonMP3"},
  {name:"LBC News London",             cat:"Talk & News", url:"https://media-ice.musicradio.com/LBCNewsLondonMP3"},
  {name:"LBC News UK",                 cat:"Talk & News", url:"https://media-ice.musicradio.com/LBCNewsUKMP3"},

  /* Gold & Oldies */
  {name:"Gold London",                 cat:"Gold & Oldies", url:"https://media-ice.musicradio.com/GoldMP3"},
  {name:"Gold UK Plus",                cat:"Gold & Oldies", url:"https://media-ice.musicradio.com/Gold-plus"},

  /* Pop */
  {name:"Riviera Radio",               cat:"Pop",         url:"https://media-ice.musicradio.com/RivieraRadioMP3"},
  {name:"Riviera Relax",               cat:"Pop",         url:"https://media-ice.musicradio.com/RivieraRelaxMP3"},
];

/* ── CATEGORY METADATA ── */
const CAT_META = {
  "Hit Music":   {emoji:"🎵", grad:"linear-gradient(135deg,#7c3aed 0%,#db2777 100%)"},
  "Heart":       {emoji:"💖", grad:"linear-gradient(135deg,#be123c 0%,#f97316 100%)"},
  "Smooth":      {emoji:"🎶", grad:"linear-gradient(135deg,#1e3a5f 0%,#0891b2 100%)"},
  "Classical":   {emoji:"🎻", grad:"linear-gradient(135deg,#78350f 0%,#d97706 100%)"},
  "Rock & Indie":{emoji:"🎸", grad:"linear-gradient(135deg,#1c1917 0%,#57534e 100%)"},
  "Talk & News": {emoji:"📰", grad:"linear-gradient(135deg,#1e293b 0%,#64748b 100%)"},
  "Gold & Oldies":{emoji:"⭐", grad:"linear-gradient(135deg,#713f12 0%,#ca8a04 100%)"},
  "Pop":         {emoji:"🌴", grad:"linear-gradient(135deg,#065f46 0%,#10b981 100%)"},
};

/* ── MOOD DATA ── */
const MOODS = [
  {name:"Chill",   desc:"Low-key & relaxed",  emoji:"🌙", grad:"linear-gradient(135deg,#0f172a,#1e3a5f)",
   stations:["Smooth Chill","Smooth Relax","Capital Chill","Classic FM Calm","Radio X Chilled","Riviera Relax"]},
  {name:"Upbeat",  desc:"Feel-good hits",      emoji:"⚡", grad:"linear-gradient(135deg,#450a0a,#7f1d1d)",
   stations:["Capital UK","Heart Dance","Big Top 40","Capital Dance","Capital XTRA UK","Heart UK"]},
  {name:"Classic", desc:"Timeless music",      emoji:"🎻", grad:"linear-gradient(135deg,#78350f,#d97706)",
   stations:["Classic FM","Classic FM Movies","Classic FM Calm","Smooth Soul","Smooth 70s","Smooth 80s"]},
  {name:"News",    desc:"Stay informed",        emoji:"📡", grad:"linear-gradient(135deg,#0c1a2e,#1e3a5f)",
   stations:["LBC UK","LBC London","LBC News UK","LBC News London"]},
];